#!/usr/bin/sh

# Set with the flags '-e', '-o pipefail' cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

path_dwm="$HOME/.local/src/dwm/config.h"


sed -nr 's/[\t]//g; /Keychord/, /\}\;/p'  $path_dwm |\
  sed -re 's/[//].*//g' \
  -e 's/[[:blank:]]//g' \
  -e 's/[{|{{|}|}}"()]//g' \
  -e 's/^([12],0,|[12],)//g' -e 's/(XF86XK_|XK_|,|spawn|\.v=)//g' |\
    sed -e 's/SHCMD/\t/g' \
      -e 's/MODKEY/⌘  + /g; s/ShiftMask/Shift + /g; s/Mod1Mask/Alt + /g; s/ControlMask/Ctrl + /g' \
      -e 's/\$BROWSER/'$BROWSER'/' \
      -e 's/st-e\|\<st\>/ /g' \
      -e 's/toggle[sticky|fullscr|gaps|bar]/\t&/' \
      -e 's/0\(\w\)/ + \1/g' \
      -e 's/^Touchpad[Off|On].*//; /Touchpad/s/sync.*/ enable\/disable/' \
      -e '/setmfact/s/\.f=//;s/\(setmfact\)\(.*\)/\t\1 \2/' \
      -e 's/shift[view|tag]\|inc[nmaster|rgaps]\|view[0-1]\|book[config|media|browser]\|tag\|focus[mon]\|killclient/\t&/g' \
      -e '/cmd/ s/dmenu\|term/\t&/g' \
      -e '/bookman/s/\t//2'\
      -e '/MYTETRA/s/MYTETRA/\L&/'\
      -e '/quit[0-1]/s/quit[0-1]/\t&/;s/quit1/reload/;s/quit0/logout/'\
      -e 's/.layouts.0./[M] monocle/' \
      -e 's/.layouts.1./[]= tile/' \
      -e 's/.layouts.3./[\\]  dwindle/' \
      -e 's/.layouts.6./|M| centeredmaster/' \
      -e 's/.layouts.7./>M>	centeredfloatingmaster/' \
      -e '/layout/s/setlayout/\t/g' \
      -e 's/togglescratch.*0/ scratch_Terminal/' \
      -e 's/togglescratch.*1/ scratch_Calculator/' \
      -e 's/togglescratch.*2/ scratch_ncmpcpp(music)/' \
      -e 's/togglescratch.*3/ scratch_cdown/' \
      -e 's/TAGKEYS.*\|STACKKEYS.*\|static.*//g; /^$/d' |\
  rofi -dmenu


